config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :members
  get 'homes/about', as: 'about'

  resources :posts, only: [:new, :create, :index, :show, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :members, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :member
  belongs_to :post

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/post.rb
class Post < ApplicationRecord
  
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :member
  
  has_one_attached :image
  
  validates :shop, presence: true
  validates :image, presence: true
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def favorited_by?(member)
    favorites.exists?(member_id: member.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_member!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    post = Post.find(params[:post_id])
    comment = Comment.new(comment_params)
    comment.member_id = current_member.id
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post.id)
  end
  
  def destroy
    Comment.find(params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    post = Post.find(params[:post_id])
    favorite = Favorite.new(member_id: current_member.id, post_id: params[:post_id])
    favorite.save
    redirect_to post_path(post.id)
  end
  
  def destroy
    post = Post.find(params[:post_id])
    favorite = Favorite.find_by(member_id: current_member.id, post_id: params[:post_id])
    favorite.destroy
    redirect_to post_path(post.id)
  end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def show
    @member = Member.find(params[:id])
    @posts = @member.posts.page(params[:pa])
  end

  def edit
    @member = Member.find(params[:id])
  end
  
  def update
    @member = Member.find(params[:id])
    @member.update(member_params)
    redirect_to member_path(@member[:id])
  end
  
  
  private
  
  def member_params
    params.require(:member).permit(:name, :profile_image)
  end
  
  def is_matching_login_user
    member_id = params[:id].to_i
    login_user = current_member.id
    if (member_id != login_user)
      redirect_to posts_path
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.member_id = current_member.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.page(params[:pa])
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:shop, :image, :caption)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="">
    <header>
    <% if member_signed_in? %>
      <li>
        <%= link_to '投稿フォーム', new_post_path %>
      </li>
      <li>
        <%= link_to 'マイページ', member_path(current_member.id) %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_member_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_member_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_member_session_path %>
      </li>
    <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/members/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @member do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit "変更を保存" %>
<% end %>

app/views/members/show.html.erb
<div>
  <h3><%= @member.name %></h3>
  <%= image_tag @member.get_profile_image(100,100) %>
  <% if @member == current_member %>
   <p><%= link_to "プロフィール編集", edit_member_path(@member.id) %></p>
  <% end %>
</div>

<%= render 'posts/list', posts: @posts %>

app/views/posts/_list.html.erb
<% posts.each do |post| %>
<div>
  <%= link_to post_path(post.id) do %>
    <%= image_tag post.get_image %>
  <% end %>

  <p>投稿ユーザー画像：<%= image_tag post.member.get_profile_image(100,100) %></p>
  <p>ショップ名：<%= post.shop %></p>
  <p>説明：<%= post.caption %></p>
  <p>ユーザーネーム：<%= post.member.name %></p>
  <p><%= link_to "#{post.comments.count} コメント", post_path(post.id) %></p>
</div>
<% end %>

<%= paginate posts %>

app/views/posts/index.html.erb
<%= render 'posts/list', posts: @posts %>

app/views/posts/new.html.erb
<h1>画像投稿フォーム</h1>
<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


  <%= form_with model: @post do |f| %>
    <h4>画像</h4>
      <%= f.file_field :image, accept: "image/*" %>
    <h4>ショップ名</h4>
      <%= f.text_field :shop %>
    <h4>説明</h4>
      <%= f.text_area :caption %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/posts/show.html.erb
<div>
  <%= image_tag @post.get_image %>
  <p>ショップ名：<%= @post.shop %></p>
  <p>説明：<%= @post.caption %></p>
  <p>投稿ユーザー画像：<%= image_tag 'sample-author1.jpg' %></p>
  <p>ユーザーネーム：<%= @post.member.name %></p>
  <p>投稿日：<%= @post.created_at.strftime('%Y年%m月%d日') %></p>
  <% if @post.member == current_member %>
    <%= link_to "削除", post_path(@post.id), method: :delete %>
  <% end %>

 <% if @post.favorited_by?(current_member) %>
    <p>
      <%= link_to post_favorites_path(@post), method: :delete do %>
        ♥<%= @post.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_favorites_path(@post), method: :post do %>
        ♡<%= @post.favorites.count %> いいね
      <% end %>
    </p>
  <% end %></div>
  
</div>


<div>
  <p>コメント件数：<%= @post.comments.count %></p>
  <% @post.comments.each do |comment| %>
    <p><%= image_tag comment.member.get_profile_image(100,100) %></p>
    <%= comment.member.name %>
    <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment_body %>
    <% if comment.member == current_member %>
      <%= link_to "削除", post_comment_path(@post, comment), method: :delete %>
    <% end %>
  <% end %>
</div>
<div>
  <%= form_with model: [@post, @comment] do |f| %>
    <%= f.text_area :comment_body, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>